"""expenses supplier bills payments

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-27 19:32:37.135443+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_expense_categories_name")),
    )
    op.create_table(
        "expenses",
        sa.Column("expense_number", sa.String(length=30), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("payee", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("submitted_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IS NULL OR method IN ('CASH', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CHEQUE', 'CARD')",
            name=op.f("ck_expenses_method_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f("ck_expenses_status_valid")
        ),
        sa.CheckConstraint(
            "amount > 0 AND tax_amount >= 0", name=op.f("ck_expenses_amounts_valid")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_expenses_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["expense_categories.id"],
            name=op.f("fk_expenses_category_id_expense_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_expenses_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
            name=op.f("fk_expenses_submitted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint("expense_number", name=op.f("uq_expenses_expense_number")),
    )
    op.create_index(op.f("ix_expenses_category_id"), "expenses", ["category_id"], unique=False)
    op.create_index(op.f("ix_expenses_expense_date"), "expenses", ["expense_date"], unique=False)
    op.create_index(op.f("ix_expenses_status"), "expenses", ["status"], unique=False)
    op.create_table(
        "supplier_bills",
        sa.Column("bill_number", sa.String(length=30), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_invoice_number", sa.String(length=100), nullable=False),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')",
            name=op.f("ck_supplier_bills_status_valid"),
        ),
        sa.CheckConstraint(
            "amount_paid >= 0 AND amount_paid <= total",
            name=op.f("ck_supplier_bills_paid_within_total"),
        ),
        sa.CheckConstraint("due_date >= bill_date", name=op.f("ck_supplier_bills_due_after_bill")),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax_total >= 0 AND total > 0",
            name=op.f("ck_supplier_bills_amounts_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_supplier_bills_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_supplier_bills_cancelled_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_supplier_bills_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_supplier_bills_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_bills_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_bills")),
        sa.UniqueConstraint("bill_number", name=op.f("uq_supplier_bills_bill_number")),
        sa.UniqueConstraint(
            "supplier_id", "supplier_invoice_number", name="uq_supplier_bills_supplier_invoice"
        ),
    )
    op.create_index(
        op.f("ix_supplier_bills_bill_date"), "supplier_bills", ["bill_date"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_bills_due_date"), "supplier_bills", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_bills_purchase_order_id"),
        "supplier_bills",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_index(op.f("ix_supplier_bills_status"), "supplier_bills", ["status"], unique=False)
    op.create_index(
        "ix_supplier_bills_supplier_status",
        "supplier_bills",
        ["supplier_id", "status"],
        unique=False,
    )
    op.create_table(
        "supplier_payments",
        sa.Column("payment_number", sa.String(length=30), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("bill_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("paid_by_id", sa.Uuid(), nullable=True),
        sa.Column("voided_by_id", sa.Uuid(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "method IN ('CASH', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CHEQUE', 'CARD')",
            name=op.f("ck_supplier_payments_method_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('POSTED', 'VOIDED')", name=op.f("ck_supplier_payments_status_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_supplier_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["supplier_bills.id"],
            name=op.f("fk_supplier_payments_bill_id_supplier_bills"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paid_by_id"],
            ["users.id"],
            name=op.f("fk_supplier_payments_paid_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_payments_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_id"],
            ["users.id"],
            name=op.f("fk_supplier_payments_voided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_payments")),
        sa.UniqueConstraint("payment_number", name=op.f("uq_supplier_payments_payment_number")),
    )
    op.create_index(
        op.f("ix_supplier_payments_bill_id"), "supplier_payments", ["bill_id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_payments_payment_date"),
        "supplier_payments",
        ["payment_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_payments_supplier_id"), "supplier_payments", ["supplier_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_payments_supplier_id"), table_name="supplier_payments")
    op.drop_index(op.f("ix_supplier_payments_payment_date"), table_name="supplier_payments")
    op.drop_index(op.f("ix_supplier_payments_bill_id"), table_name="supplier_payments")
    op.drop_table("supplier_payments")
    op.drop_index("ix_supplier_bills_supplier_status", table_name="supplier_bills")
    op.drop_index(op.f("ix_supplier_bills_status"), table_name="supplier_bills")
    op.drop_index(op.f("ix_supplier_bills_purchase_order_id"), table_name="supplier_bills")
    op.drop_index(op.f("ix_supplier_bills_due_date"), table_name="supplier_bills")
    op.drop_index(op.f("ix_supplier_bills_bill_date"), table_name="supplier_bills")
    op.drop_table("supplier_bills")
    op.drop_index(op.f("ix_expenses_status"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_expense_date"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_category_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_table("expense_categories")
    # ### end Alembic commands ###
