"""sales invoices payments

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-27 19:23:08.937305+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_invoices",
        sa.Column("invoice_number", sa.String(length=30), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("customer_reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')",
            name=op.f("ck_sales_invoices_status_valid"),
        ),
        sa.CheckConstraint(
            "amount_paid >= 0 AND amount_paid <= total",
            name=op.f("ck_sales_invoices_paid_within_total"),
        ),
        sa.CheckConstraint(
            "due_date >= invoice_date", name=op.f("ck_sales_invoices_due_after_invoice")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_sales_invoices_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_sales_invoices_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_sales_invoices_cancelled_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_sales_invoices_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_sales_invoices_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_sales_invoices_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_invoices")),
        sa.UniqueConstraint("invoice_number", name=op.f("uq_sales_invoices_invoice_number")),
    )
    op.create_index(
        "ix_sales_invoices_customer_status",
        "sales_invoices",
        ["customer_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_invoices_due_date"), "sales_invoices", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_sales_invoices_invoice_date"), "sales_invoices", ["invoice_date"], unique=False
    )
    op.create_index(op.f("ix_sales_invoices_status"), "sales_invoices", ["status"], unique=False)
    op.create_table(
        "customer_payments",
        sa.Column("receipt_number", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("received_by_id", sa.Uuid(), nullable=True),
        sa.Column("voided_by_id", sa.Uuid(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "method IN ('CASH', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CHEQUE', 'CARD')",
            name=op.f("ck_customer_payments_method_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('POSTED', 'VOIDED')", name=op.f("ck_customer_payments_status_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_customer_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_payments_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoices.id"],
            name=op.f("fk_customer_payments_invoice_id_sales_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_id"],
            ["users.id"],
            name=op.f("fk_customer_payments_received_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_id"],
            ["users.id"],
            name=op.f("fk_customer_payments_voided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_payments")),
        sa.UniqueConstraint("receipt_number", name=op.f("uq_customer_payments_receipt_number")),
    )
    op.create_index(
        op.f("ix_customer_payments_customer_id"), "customer_payments", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_payments_invoice_id"), "customer_payments", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_payments_payment_date"),
        "customer_payments",
        ["payment_date"],
        unique=False,
    )
    op.create_table(
        "sales_invoice_lines",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_tax", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "discount_percent >= 0 AND discount_percent <= 100",
            name=op.f("ck_sales_invoice_lines_discount_valid"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_invoice_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_sales_invoice_lines_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoices.id"],
            name=op.f("fk_sales_invoice_lines_invoice_id_sales_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sales_invoice_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_invoice_lines")),
    )
    op.create_index(
        op.f("ix_sales_invoice_lines_invoice_id"),
        "sales_invoice_lines",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_invoice_lines_product_id"),
        "sales_invoice_lines",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_invoice_lines_product_id"), table_name="sales_invoice_lines")
    op.drop_index(op.f("ix_sales_invoice_lines_invoice_id"), table_name="sales_invoice_lines")
    op.drop_table("sales_invoice_lines")
    op.drop_index(op.f("ix_customer_payments_payment_date"), table_name="customer_payments")
    op.drop_index(op.f("ix_customer_payments_invoice_id"), table_name="customer_payments")
    op.drop_index(op.f("ix_customer_payments_customer_id"), table_name="customer_payments")
    op.drop_table("customer_payments")
    op.drop_index(op.f("ix_sales_invoices_status"), table_name="sales_invoices")
    op.drop_index(op.f("ix_sales_invoices_invoice_date"), table_name="sales_invoices")
    op.drop_index(op.f("ix_sales_invoices_due_date"), table_name="sales_invoices")
    op.drop_index("ix_sales_invoices_customer_status", table_name="sales_invoices")
    op.drop_table("sales_invoices")
    # ### end Alembic commands ###
