"""fixed assets

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-27 19:36:23.718971+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("depreciation_method", sa.String(length=20), nullable=False),
        sa.Column("useful_life_months", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "depreciation_method IN ('STRAIGHT_LINE', 'NONE')",
            name=op.f("ck_asset_categories_method_valid"),
        ),
        sa.CheckConstraint(
            "useful_life_months > 0", name=op.f("ck_asset_categories_life_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_asset_categories_name")),
    )
    op.create_table(
        "assets",
        sa.Column("asset_tag", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_employee_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("purchase_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("salvage_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("depreciation_method", sa.String(length=20), nullable=False),
        sa.Column("useful_life_months", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("disposal_date", sa.Date(), nullable=True),
        sa.Column("disposal_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("disposal_reason", sa.Text(), nullable=True),
        sa.Column("disposed_by_id", sa.Uuid(), nullable=True),
        sa.Column("disposed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "depreciation_method IN ('STRAIGHT_LINE', 'NONE')", name=op.f("ck_assets_method_valid")
        ),
        sa.CheckConstraint(
            "status IN ('IN_USE', 'IN_STORE', 'UNDER_MAINTENANCE', 'DISPOSED')",
            name=op.f("ck_assets_status_valid"),
        ),
        sa.CheckConstraint(
            "disposal_date IS NULL OR disposal_date >= purchase_date",
            name=op.f("ck_assets_disposal_after_purchase"),
        ),
        sa.CheckConstraint("purchase_cost >= 0", name=op.f("ck_assets_cost_non_negative")),
        sa.CheckConstraint(
            "salvage_value >= 0 AND salvage_value <= purchase_cost",
            name=op.f("ck_assets_salvage_valid"),
        ),
        sa.CheckConstraint("useful_life_months > 0", name=op.f("ck_assets_life_positive")),
        sa.ForeignKeyConstraint(
            ["assigned_employee_id"],
            ["employees.id"],
            name=op.f("fk_assets_assigned_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_assets_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["asset_categories.id"],
            name=op.f("fk_assets_category_id_asset_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["disposed_by_id"],
            ["users.id"],
            name=op.f("fk_assets_disposed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_assets_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("asset_tag", name=op.f("uq_assets_asset_tag")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_assets_serial_number")),
    )
    op.create_index(
        op.f("ix_assets_assigned_employee_id"), "assets", ["assigned_employee_id"], unique=False
    )
    op.create_index(op.f("ix_assets_category_id"), "assets", ["category_id"], unique=False)
    op.create_index(op.f("ix_assets_name"), "assets", ["name"], unique=False)
    op.create_index(op.f("ix_assets_status"), "assets", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assets_status"), table_name="assets")
    op.drop_index(op.f("ix_assets_name"), table_name="assets")
    op.drop_index(op.f("ix_assets_category_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_assigned_employee_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_table("asset_categories")
    # ### end Alembic commands ###
