"""quotations and tax-inclusive prices

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-27 20:57:18.100161+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotations",
        sa.Column("quote_number", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("quote_date", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("prices_include_tax", sa.Boolean(), nullable=False),
        sa.Column("customer_reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SENT', 'ACCEPTED', 'DECLINED', 'CONVERTED')",
            name=op.f("ck_quotations_status_valid"),
        ),
        sa.CheckConstraint(
            "valid_until >= quote_date", name=op.f("ck_quotations_valid_after_quote")
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_quotations_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_quotations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_quotations_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoices.id"],
            name=op.f("fk_quotations_invoice_id_sales_invoices"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotations")),
        sa.UniqueConstraint("quote_number", name=op.f("uq_quotations_quote_number")),
    )
    op.create_index(
        "ix_quotations_customer_status", "quotations", ["customer_id", "status"], unique=False
    )
    op.create_index(op.f("ix_quotations_quote_date"), "quotations", ["quote_date"], unique=False)
    op.create_index(op.f("ix_quotations_status"), "quotations", ["status"], unique=False)
    op.create_table(
        "quotation_lines",
        sa.Column("quotation_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_tax", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "discount_percent >= 0 AND discount_percent <= 100",
            name=op.f("ck_quotation_lines_discount_valid"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_quotation_lines_quantity_positive")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_quotation_lines_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_quotation_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_quotation_lines_quotation_id_quotations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_lines")),
    )
    op.create_index(
        op.f("ix_quotation_lines_product_id"), "quotation_lines", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_quotation_lines_quotation_id"), "quotation_lines", ["quotation_id"], unique=False
    )
    op.add_column(
        "sales_invoices",
        sa.Column("prices_include_tax", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales_invoices", "prices_include_tax")
    op.drop_index(op.f("ix_quotation_lines_quotation_id"), table_name="quotation_lines")
    op.drop_index(op.f("ix_quotation_lines_product_id"), table_name="quotation_lines")
    op.drop_table("quotation_lines")
    op.drop_index(op.f("ix_quotations_status"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_quote_date"), table_name="quotations")
    op.drop_index("ix_quotations_customer_status", table_name="quotations")
    op.drop_table("quotations")
    # ### end Alembic commands ###
